databases:
  - name: simple-app-db
    databaseName: simpleapp
    user: simpleapp
    plan: free
    region: frankfurt

services:
  - type: web
    name: simple-app
    runtime: docker
    region: frankfurt
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: simple-app-db
          property: connectionString
